server:
  port: 8011
spring:
  application:
    name: provider #服务注册在 Eureka Server 上的名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # 注册中心的地址
  instance:
    prefer-ip-address: true # 是否将当前服务的ip注册到 Eureka Server