server:
  port: 8761
eureka:
  client:
    register-with-eureka: false # 是否在eureka中注册该服务（对于本服务来说就是是否注册自己）
    fetch-registry: false # 是否同步其他注册中心的数据
    service-url:
      defaultZone: http://localhost:8761/eureka/